# Constants for Noun Phrases
#   Forms in Noun Phrases
NOUN = 'NOUN'
DETERMINER = 'DETERMINER'
ADJECTIVE = 'ADJECTIVE'
#   Functions of Noun Phrases
DIRECT_OBJECT = 'DIRECT_OBJECT'
INDIRECT_OBJECT = 'INDIRECT_OBJECT'
SUBJECT = 'SUBJECT'
SUBJECT_COMPLIMENT = 'SUBJECT_COMPLIMENT'
OBJECT_COMPLIMENT = 'OBJECT_COMPLIMENT'
OBJECT_OF_PREPOSITION = 'OBJECT_OF_PREPOSITION'

# Constants for Verb Phrases
# Forms in Verb Phrases
VERB = 'VERB'
ADVERB = 'ADVERB'
PREP_PHRASE = 'PREP_PHRASE'
# Functions in Verb Phrases
GERUND = 'GERUND'
PARTICIPLE = 'PARTICIPLE'
TRANSITIVE = 'TRANSITIVE'
INTRANSITIVE = 'INTRANSITIVE'
LINKING = 'LINKING'
BE = 'BE'

# Constants for Prepositional Phrases
PREPOSITION = 'PREPOSITION'

# Constants for Verbs and Verb Agreement
# Tense
PAST = 'PAST'
PRESENT = 'PRESENT'
# Aspect
PERFECT = 'PERFECT'
PROGRESSIVE = 'PROGRESSIVE'
# Mood
CONDITIONAL = 'CONDITIONAL'
SUBJUNCTIVE = 'SUBJUNCTIVE'
# Voice
PASSIVE = 'PASSIVE'
ACTIVE = 'ACTIVE'
# Person
FIRST_PERSON = 'FIRST_PERSON'
SECOND_PERSON = 'SECOND_PERSON'
THIRD_PERSON = 'THIRD_PERSON'
# Singular/Plural
SINGULAR = 'SINGULAR'
PLURAL = 'PLURAL'

# Path to Project
path = "C:/Users/gavyn/Documents/Python/HaikuGrammar"
