# Constants for Noun Phrases
# Form
NOUN = 'NOUN'
DETERMINER = 'DETERMINER'
ADJECTIVE = 'ADJECTIVE'
# Function
DIRECT_OBJECT = 'DIRECT_OBJECT'
INDIRECT_OBJECT = 'INDIRECT_OBJECT'
SUBJECT = 'SUBJECT'

# Constants for Verb Phrases
VERB = 'VERB'
TRANSITIVE = 'TRANSITIVE'
INTRANSITIVE = 'INTRANSITIVE'
LINKING = 'LINKING'

# Constants for Prepositional Phrases
PREPOSITION = 'PREPOSITION'

# Constants for Verbs and Verb Agreement
# Tense
PAST = 'PAST'
PRESENT = 'PRESENT'
# Aspect
PERFECT = 'PERFECT'
PROGRESSIVE = 'PROGRESSIVE'
# Mood
CONDITIONAL = 'CONDITIONAL'
SUBJUNCTIVE = 'SUBJUNCTIVE'
# Voice
PASSIVE = 'PASSIVE'
ACTIVE = 'ACTIVE'
# Person
FIRST_PERSON = 'FIRST_PERSON'
SECOND_PERSON = 'SECOND_PERSON'
THIRD_PERSON = 'THIRD_PERSON'
# Singular/Plural
SINGULAR = 'SINGULAR'
PLURAL = 'PLURAL'
# Verb Types
BE = 'BE'
ADVERB = 'ADVERB'
GERUND = 'GERUND'
PREP_PHRASE = 'PREP_PHRASE'

# Path to Project
path = "C:/Users/gavyn/Documents/Python/HaikuGrammar"
